name: courseit
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  lottie: ^2.0.0
  http: ^1.2.1 
  geolocator: ^11.0.0
  camera: ^0.10.5+9
  path_provider: ^2.1.2
  image_picker: ^1.1.0

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/logo.png
    - assets/animations/animation_not_found.json
    - assets/animations/animation_user.json
    - assets/animations/animation_create_course.json
    - assets/animations/animation_location.json
